const actionType = {
  LOAD_DATA: 'LOAD_DATA',
  LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
  LOAD_DATA_FAILURE: 'LOAD_DATA_FAILURE',
  SET_INCREMENT: 'SET_INCREMENT',
  SET_DECREMENT: 'SET_DECREMENT',
  CHECKOUT_PRODUCT: 'CHECKOUT_PRODUCT'
};

export default actionType;
